##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Floating windows
windowrule = match:class org.pulseaudio.pavucontrol, float 1
windowrule = match:class org.pulseaudio.pavucontrol, size 700 500
windowrule = match:class org.pulseaudio.pavucontrol, move monitor_w-712 48

# Opacity
windowrule = match:class org.gnome.Nautilus, opacity 0.9 0.9
windowrule = match:class code, opacity 0.9 0.9,
windowrule = match:class antigravity-ide, opacity 0.9 0.9
windowrule = match:class discord, opacity 0.8 0.8
windowrule = match:class Spotify, opacity 0.8 0.8
windowrule = match:class nm-connection-editor, opacity 0.8 0.8
windowrule = match:class Slack, opacity 0.8 0.8
windowrule = match:class teams-for-linux, opacity 0.8 0.8
windowrule = match:class signal, opacity 0.8 0.8
windowrule = match:class org.pulseaudio.pavucontrol, opacity 0.8 0.8
